// src/constants/countries.ts

export interface Country {
  name: string;
  code: string;
  iso: string;
}

export const ALL_COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "+93", iso: "AF" },
  { name: "Albania", code: "+355", iso: "AL" },
  { name: "Algeria", code: "+213", iso: "DZ" },
  { name: "Andorra", code: "+376", iso: "AD" },
  { name: "Angola", code: "+244", iso: "AO" },
  { name: "Argentina", code: "+54", iso: "AR" },
  { name: "Armenia", code: "+374", iso: "AM" },
  { name: "Australia", code: "+61", iso: "AU" },
  { name: "Austria", code: "+43", iso: "AT" },
  { name: "Azerbaijan", code: "+994", iso: "AZ" },
  { name: "Bahrain", code: "+973", iso: "BH" },
  { name: "Bangladesh", code: "+880", iso: "BD" },
  { name: "Belarus", code: "+375", iso: "BY" },
  { name: "Belgium", code: "+32", iso: "BE" },
  { name: "Bhutan", code: "+975", iso: "BT" },
  { name: "Bolivia", code: "+591", iso: "BO" },
  { name: "Brazil", code: "+55", iso: "BR" },
  { name: "Bulgaria", code: "+359", iso: "BG" },
  { name: "Cambodia", code: "+855", iso: "KH" },
  { name: "Cameroon", code: "+237", iso: "CM" },
  { name: "Canada", code: "+1", iso: "CA" },
  { name: "Chile", code: "+56", iso: "CL" },
  { name: "China", code: "+86", iso: "CN" },
  { name: "Colombia", code: "+57", iso: "CO" },
  { name: "Costa Rica", code: "+506", iso: "CR" },
  { name: "Croatia", code: "+385", iso: "HR" },
  { name: "Cuba", code: "+53", iso: "CU" },
  { name: "Cyprus", code: "+357", iso: "CY" },
  { name: "Czech Republic", code: "+420", iso: "CZ" },
  { name: "Denmark", code: "+45", iso: "DK" },
  { name: "Dominican Republic", code: "+1", iso: "DO" },
  { name: "Ecuador", code: "+593", iso: "EC" },
  { name: "Egypt", code: "+20", iso: "EG" },
  { name: "Estonia", code: "+372", iso: "EE" },
  { name: "Ethiopia", code: "+251", iso: "ET" },
  { name: "Finland", code: "+358", iso: "FI" },
  { name: "France", code: "+33", iso: "FR" },
  { name: "Georgia", code: "+995", iso: "GE" },
  { name: "Germany", code: "+49", iso: "DE" },
  { name: "Ghana", code: "+233", iso: "GH" },
  { name: "Greece", code: "+30", iso: "GR" },
  { name: "Hong Kong", code: "+852", iso: "HK" },
  { name: "Hungary", code: "+36", iso: "HU" },
  { name: "Iceland", code: "+354", iso: "IS" },
  { name: "India", code: "+91", iso: "IN" },
  { name: "Indonesia", code: "+62", iso: "ID" },
  { name: "Iran", code: "+98", iso: "IR" },
  { name: "Iraq", code: "+964", iso: "IQ" },
  { name: "Ireland", code: "+353", iso: "IE" },
  { name: "Israel", code: "+972", iso: "IL" },
  { name: "Italy", code: "+39", iso: "IT" },
  { name: "Jamaica", code: "+1", iso: "JM" },
  { name: "Japan", code: "+81", iso: "JP" },
  { name: "Jordan", code: "+962", iso: "JO" },
  { name: "Kazakhstan", code: "+7", iso: "KZ" },
  { name: "Kenya", code: "+254", iso: "KE" },
  { name: "Kuwait", code: "+965", iso: "KW" },
  { name: "Latvia", code: "+371", iso: "LV" },
  { name: "Lebanon", code: "+961", iso: "LB" },
  { name: "Libya", code: "+218", iso: "LY" },
  { name: "Lithuania", code: "+370", iso: "LT" },
  { name: "Luxembourg", code: "+352", iso: "LU" },
  { name: "Malaysia", code: "+60", iso: "MY" },
  { name: "Maldives", code: "+960", iso: "MV" },
  { name: "Malta", code: "+356", iso: "MT" },
  { name: "Mauritius", code: "+230", iso: "MU" },
  { name: "Mexico", code: "+52", iso: "MX" },
  { name: "Monaco", code: "+377", iso: "MC" },
  { name: "Mongolia", code: "+976", iso: "MN" },
  { name: "Morocco", code: "+212", iso: "MA" },
  { name: "Nepal", code: "+977", iso: "NP" },
  { name: "Netherlands", code: "+31", iso: "NL" },
  { name: "New Zealand", code: "+64", iso: "NZ" },
  { name: "Nigeria", code: "+234", iso: "NG" },
  { name: "Norway", code: "+47", iso: "NO" },
  { name: "Oman", code: "+968", iso: "OM" },
  { name: "Pakistan", code: "+92", iso: "PK" },
  { name: "Panama", code: "+507", iso: "PA" },
  { name: "Peru", code: "+51", iso: "PE" },
  { name: "Philippines", code: "+63", iso: "PH" },
  { name: "Poland", code: "+48", iso: "PL" },
  { name: "Portugal", code: "+351", iso: "PT" },
  { name: "Qatar", code: "+974", iso: "QA" },
  { name: "Romania", code: "+40", iso: "RO" },
  { name: "Russia", code: "+7", iso: "RU" },
  { name: "Saudi Arabia", code: "+966", iso: "SA" },
  { name: "Singapore", code: "+65", iso: "SG" },
  { name: "Slovakia", code: "+421", iso: "SK" },
  { name: "Slovenia", code: "+386", iso: "SI" },
  { name: "South Africa", code: "+27", iso: "ZA" },
  { name: "South Korea", code: "+82", iso: "KR" },
  { name: "Spain", code: "+34", iso: "ES" },
  { name: "Sri Lanka", code: "+94", iso: "LK" },
  { name: "Sweden", code: "+46", iso: "SE" },
  { name: "Switzerland", code: "+41", iso: "CH" },
  { name: "Taiwan", code: "+886", iso: "TW" },
  { name: "Thailand", code: "+66", iso: "TH" },
  { name: "Turkey", code: "+90", iso: "TR" },
  { name: "Ukraine", code: "+380", iso: "UA" },
  { name: "United Arab Emirates", code: "+971", iso: "AE" },
  { name: "United Kingdom", code: "+44", iso: "GB" },
  { name: "United States", code: "+1", iso: "US" },
  { name: "Uruguay", code: "+598", iso: "UY" },
  { name: "Uzbekistan", code: "+998", iso: "UZ" },
  { name: "Venezuela", code: "+58", iso: "VE" },
  { name: "Vietnam", code: "+84", iso: "VN" },
];